ruff check --unsafe-fixes --fix --show-fixes . (ACHTUNG: causes test BREAKAGE)
Ruff unsafe fix is really unsafe: in this case it is not straightforward to
replace this expression:
    x = x + 1
with this one:
    x += 1

Fixed 14 errors:
- black_it/calibrator.py:
    3 × PLR6104 (non-augmented-assignment)
- black_it/loss_functions/gsl_div.py:
    3 × PLR6104 (non-augmented-assignment)
- black_it/loss_functions/msm.py:
    2 × PLR6104 (non-augmented-assignment)
- black_it/samplers/halton.py:
    1 × PLR6104 (non-augmented-assignment)
- black_it/samplers/random_forest.py:
    1 × PLR6104 (non-augmented-assignment)
- examples/models/economics/brock_hommes.py:
    2 × PLR6104 (non-augmented-assignment)
- examples/models/simple_models.py:
    2 × PLR6104 (non-augmented-assignment)

Found 30 errors (14 fixed, 16 remaining).

==========================
These tests are now failing:

FAILED black_it/loss_functions/gsl_div.py::black_it.loss_functions.gsl_div.GslDivLoss
FAILED black_it/loss_functions/gsl_div.py::black_it.loss_functions.gsl_div.GslDivLoss.get_words
FAILED tests/test_losses/test_gsl.py::test_gsl_with_nb_values - numpy.core._exceptions._UFuncOutputCastingError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'
FAILED tests/test_losses/test_gsl.py::test_gsl_default - numpy.core._exceptions._UFuncOutputCastingError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'
FAILED tests/test_losses/test_gsl.py::TestGetWords::test_get_words - numpy.core._exceptions._UFuncOutputCastingError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'
FAILED tests/test_examples/test_sir_python.py::test_sir_w_breaks - FileNotFoundError: [Errno 2] No such file or directory: '/home/muxator/code/abm/black-it/tests/fixtures/data/test_sir_w_breaks_python.npy'
============================================================================= 6 failed, 98 passed, 2 skipped, 1 deselected, 1555 warnings in 103.38s (0:01:43) =============================================================================